export const GET_NETFLIX_ORIGINALS = "GET_NETFLIX_ORIGINALS";
export const GET_TRENDING_MOVIES = "GET_TRENDING_MOVIES";
export const GET_TOPRATE_MOVIES = "GET_TOPRATE_MOVIES";
export const GET_UPCOMING_MOVIES = "GET_UPCOMING_MOVIES";
export const GET_NOWPLAYING_MOVIES = "GET_NOWPLAYING_MOVIES";
export const GET_SEARCH_MOVIES = "GET_SEARCH_MOVIES";
export const GET_ACTION_MOVIES = "GET_ACTION_MOVIES";
export const GET_COMEDY_MOVIES = "GET_COMEDY_MOVIES";

export const SET_MOVIE_DETAIL = "SET_MOVIE_DETAIL";
